apiVersion: v1
kind: Service
metadata:
  name: httpecho-service
spec:
  type: ClusterIP
  selector:
    app: httpecho
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.container.port }}
    