apiVersion: v1
kind: Service
metadata:
  name: httpecho-service
  #namespace: default
spec:
  ports:
  - port: 11323
    protocol: TCP
    targetPort: 1323
  selector:
    pod: httpecho-pod
  # sessionAffinity: None
  # type: LoadBalancer
