apiVersion: v1
kind: Pod
metadata:
  name: httpecho-pod
  labels:
    name: httpecho-pod
    pod: httpecho-pod
spec:
  containers:
  - name: httpecho
    image: devbfvio/httpecho:v0.1.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 1323
    env:
      - name: INSTANCE_NAME
        value: echo-1
  
